# Generated by Django 3.0.7 on 2020-06-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20200622_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug_slug', editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='slug', editable=False, max_length=100),
        ),
    ]
