# Generated by Django 3.0.7 on 2020-06-30 20:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20200629_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
